[package]
name = "arrowyn"
version = "0.1.0"
edition = "2024"

[lib]
name = "_core"
# "cdylib" is necessary to produce a shared library for Python to import from.
crate-type = ["cdylib"]

[dependencies]
arrow = { version = "60.0.0", default-features = false, features = ["ipc"] }
bincode-next = "3.1.1"
crossbeam-channel = "0.5.17"
memchr = "2.8"
memmap2 = "0.9.11"
pyo3 = { version = "0.29.2", features = ["extension-module"] }
pyo3-arrow = "0.19.0"
thiserror = "2.0.20"
